import logging
import unittest
import time
from datetime import datetime

# --- IMPORTS ---
# We bring in the code we want to test from your other files

from ipp.exercises.labmodule05.LocationData import LocationData
from ipp.exercises.labmodule05.TimeAndDateUtil import TimeAndDateUtil
from ipp.exercises.labmodule05.WeatherData import WeatherData

class TimeAndDateUtilTest(unittest.TestCase):
    @classmethod
    
    def setUpClass(cls):
        logging.basicConfig(format = '%(asctime)s:%(module)s:%(levelname)s:%(message)s', level = logging.DEBUG)
        logging.info("Testing TimeAndDateUtil class...")
        
    def setUp(self):
        pass
        
    def tearDown(self):
        pass

    def testWeatherDataContainerDefaultValues(self):
        """
        Goal: Make sure a brand new 'WeatherData' object starts with 
        clean, empty values (0.0 or empty strings).
        """
        # Create a 'blank' weather object
        wData = WeatherData()
        # Get the current time string from our Utility class
        isoTimeDate = TimeAndDateUtil.getCurrentIso8601LocalDate()
    

        # 1. Check basic strings are empty ("")
        self.assertEqual(wData.source, "")
        self.assertEqual(wData.url, "")
        self.assertEqual(wData.description, "")

        # 2. Check numerical values are exactly 0.0
        self.assertEqual(wData.temperature, 0.0)
        self.assertEqual(wData.humidity, 0.0)
        self.assertEqual(wData.pressure, 0.0)
        self.assertEqual(wData.windspeed, 0.0)

        # 3. Time Comparison:
        # We turn the strings into 'timestamps' (numbers) so we can do math on them
        timestampA = datetime.fromisoformat(wData.timestamp).timestamp()
        timestampB = datetime.fromisoformat(isoTimeDate).timestamp()
        
        # We allow a 5-second 'wiggle room' (delta) because the computer 
        # takes a tiny bit of time to run between lines.
        self.assertAlmostEqual(timestampA, timestampB, delta=5.0)
        
        # 4. Check that a location object was actually created inside WeatherData
        self.assertIsNotNone(wData.location)

    def testGetCurrentIso8601LocalDate(self):
        """
        Goal: Verify that our custom 'getCurrentIso8601LocalDate' method 
        matches the standard Python library format.
        """
        # A: The date/time generated by YOUR code
        curIso8601DateA = TimeAndDateUtil.getCurrentIso8601LocalDate()
        
        # B: The date/time generated by Python's built-in 'datetime' library
        # We use .replace(microsecond=0) to ignore the tiny fractions of a second
        curIso8601DateB = datetime.fromtimestamp(time.time()).replace(microsecond=0).isoformat()

        # If A and B are the same string, your code is working perfectly!
        self.assertEqual(curIso8601DateA, curIso8601DateB)


    def testGetIso8601DateFromMillis(self):
        """
        Goal: Verify that if we give our code a number (milliseconds), 
        it turns it into the correct readable date string.
        """
        # Get the current time in seconds right now
        curDateInSecs = time.time()

        # Test YOUR method (converting seconds to millis by multiplying by 1000)
        curIso8601DateA = TimeAndDateUtil.getIso8601DateFromMillis(curDateInSecs * 1000)
        
        # Manual comparison using the standard Python way
        curIso8601DateB = datetime.fromtimestamp(curDateInSecs).replace(microsecond=0).isoformat()

        # The results should match
        self.assertEqual(curIso8601DateA, curIso8601DateB)

# This boilerplate code tells Python to run the tests when we hit 'Start'
if __name__ == '__main__':
    unittest.main()